var arrNames = [
  "George Floyd.",
  "Ahmaud Arbery.",
  "Breonna Taylor.",
  "Yolanda Thomas.",
  "Xavier Tyrell Johnson.",
  "Darrell Banks.",
  "Cedrick Chatman.",
  "Quintine Barksdale.",
  "Jayvis Benjamin.",
  "Donovan Thomas.",
  "Anthony Dwayne Harris.",
  "Charles A. Baker Jr.",
  "Clinton Roebexar Allen.",
  "Willie Lee Bingham Jr.",
  "Russel Lydell Smith.",
  "Dylan Samuel-Peters.",
  "Dason Peters.",
  "Craig Demps.",
  "Fred Bradford Jr.",
  "Clifton Armstrong.",
  "Deion Fludd.",
  "Kendra Diggs.",
  "Marlon Brown.",
  "Jordan Davis.",
  "Jermaine Darden.",
  "Terry Laffitte.",
  "Julian Dawkins.",
  "Philando Castile.",
  "Bill Jackson.",
  "Keoshia L. Hill.",
  "Lana Morris.",
  "Micah Anthony Key.",
  "George Harvey.",
  "Antonio Johnson.",
  "Daryll Blair.",
  "Tyrone West.",
  "Deomain Hayman.",
  "Dainell Simmons.",
  "Larry Eugene Jackson Jr.",
  "Ryan L. Stokes.",
  "Allen Desdunes.",
  "Jermaine McBean.",
  "Jeffery B Lilly Jr.",
  "Montrell Moss.",
  "Ronnie Ledesma Jr.",
  "Marlon Horton.",
  "Jonathan A. Ferrell.",
  "Alexander Jamar Marion.",
  "Elijah Glay.",
  "Jack Lamar Roberson.",
  "Reginald Williams Jr.",
  "Brandon Devone Smith.",
  "William Taylor.",
  "William Alfred Harvey III.",
  "Abdul Kamal.",
  "Willie James Williams.",
  "Ervin Edwards.",
  "Cimarron Lamar Lamb.",
  "Kendall Alexander.",
  "Jeffery Ragland.",
  "Jordan Baker.",
  "Anesson Joseph.",
  "Willie James Sams.",
  "Anthony Bartley.",
  "Ernest Satter-White.",
  "Yvette Smith.",
  "Treon Johnson.",
  "Floyd Gene Hodge.",
  "Hallis Kinsey.",
  "Willie Neall Harden.",
  "DeAndre Lloyd Starks.",
  "Zikarious Flint.",
  "Gregory Lewis Towns Jr.",
  "Tyrone Davis.",
  "Justin Griffin.",
  "George V. King.",
  "Dominique Franklin Jr.",
  "Howard Wallace Bowe Jr.",
  "Jonathan Lee Asuzu.",
  "Tommy J. Yancy Jr.",
  "Montez Dewayne Hambric.",
  "Mark Anthony Blocker.",
  "Emanuel Jean-Baptiste.",
  "Juan May.",
  "Lavon King.",
  "Jerry Brown.",
  "Christopher Jones.",
  "Charles K. Goodridge.",
  "Eric Garner.",
  "Briatay McDuffle.",
  "Jamee Johnson.",
  "Jacorey Calhoun.",
  "Cederic Stanley.",
  "Jeremey Lake.",
  "John H. Crawford III.",
  "Michael Brown.",
  "Dustin Keith Glover.",
  "Ezell Ford.",
  "Dante Parker.",
  "Corey Lavert Tanner.",
  "Levon Leroy Love.",
  "Arvel Douglas Williams.",
  "Vernicia Woodard.",
  "Cortez Washington.",
  "Darrian Nathaniel Hunt.",
  "Ricky Deangelo Hinkle.",
  "Cameron Tillman.",
  "Eugene Williams.",
  "Oliver Jarred Gregoire.",
  "Marlon S. Woodstock.",
  "Lashano J. Gilbert.",
  "Balantine Mbegbu.",
  "Iretha Lilly.",
  "VonDerrit D. Myers Jr.",
  "Adam Ardett Madison.",
  "Michael Ricardo Minor.",
  "Kaldrick Donald.",
  "John T. Wilson II.",
  "Raphael Thomas.",
  "Tanisha N. Anderson.",
  "Keara Crowder.",
  "Trayvon Martin.",
  "Akai Gurley.",
  "Tamir E. Rice.",
  "Eric Ricks.",
  "Rumain Brisbon.",
  "Dennis Grisby.",
  "David Andre Scott.",
  "Jerame Reid.",
  "Brian Pickett.",
  "Leslie Sapp II.",
  "Andre Larone Murphy Jr.",
  "Artago Damon Howard.",
  "Tiano Meton.",
  "Jeremy Lett.",
  "Natasha McKenna.",
  "Lavall Hall.",
  "Sandra Bland.",
  "Terry Price.",
  "Calvon A. Reid.",
  "Thomas Allen Jr.",
  "Deontre L. Dorsey.",
  "Charley Leundeu Keunang.",
  "Naeschylus Vinzant.",
  "Tony Terrell Robinson.",
  "Anthony Hill.",
  "Terrance Moxley.",
  "Bobby Gross.",
  "Askari Roberts.",
  "Brandon Jones.",
  "Denzel Brown.",
  "Jason Moland.",
  "Phillip White.",
  "Donald Ivy.",
  "Eric Courtney Harris.",
  "Walter Scott.",
  "Darell Lawrence Brown.",
  "Norman Cooper.",
  "William Chapman II.",
  "David Felix.",
  "Reginald L. Moore Sr.",
  "Brendon Glenn.",
  "Dajuan Graham.",
  "D’Angelo Reyes Stallsworth.",
  "Richard Gregory Davis.",
  "Ross Anthony.",
  "Kevin Higgenbotham.",
  "Kris Jacksons.",
  "Kevin Bajoie.",
  "Spencer McCain.",
  "Victo Lorosa III.",
  "Jonathan Sanders.",
  "Freddie Blue.",
  "Greorge Mann.",
  "Salvado Ellswood.",
  "Albert Joseph Davis.",
  "Darrius Stewart.",
  "Samuel Dubose.",
  "Brian Keith Day.",
  "Troy Robinson.",
  "Christian Taylor.",
  "Asshams Pharoah Manley.",
  "Mansur Ball-Bey.",
  "Felix Kumi.",
  "James Carney III.",
  "India Kager.",
  "La'Vante Trevon Biggs.",
  "Wayne Wheeler.",
  "Keith Harrison McLeod.",
  "Junior Prosper.",
  "Paterson Brown Jr.",
  "Rayshaun Cole.",
  "Lamontez Jones.",
  "Dominic Hutchinson.",
  "Anthony Ashford.",
  "Alonzo Smith.",
  "Jamar Clark.",
  "Richard Perkins.",
  "Tiara Thomas.",
  "Cornelieus Brown.",
  "Nathaniel Harris Pickett.",
  "Miguel Espinal.",
  "Leroy Browning.",
  "Michael Noel.",
  "Kevin Mathews.",
  "Bettie Jones.",
  "Keith Childress Jr.",
  "Peter John.",
  "Antronie Scott.",
  "Wendell Celestine Jr.",
  "David Joseph.",
  "Dyzhawn L. Perkins.",
  "Calin Devante Roquemore.",
  "Paul Gaston.",
  "Thomas Lane.",
  "Christopher J. Davis.",
  "Kionte DeShaun Spencer.",
  "Arteair Porter.",
  "Peter William Gaines.",
  "Torrey Lamar Robinson.",
  "India M. Beaty.",
  "Robert Dentmond.",
  "Dominique Silva.",
  "Kevin Hicks.",
  "Charlin Charles.",
  "Lionel Gibson.",
  "Arthur R. Williams Jr.",
  "Jessica Williams.",
  "Vernell Bing Jr.",
  "Michael Eugene Wilson Jr.",
  "Ollie Lee Brooks.",
  "Antwun Shumpert.",
  "Deravis Rogers.",
  "Sherman Evans.",
  "Delrawn Small.",
  "Dalvin Hollins.",
  "Donnell Thompson Jr.",
  "Kendrick Brown.",
  "Levonia Riggins.",
  "Tyre King.",
  "Terrence Crutcher.",
  "Tawon Boyd.",
  "Alfred Olango.",
  "Roy Lee Richards.",
  "Lamont Perry.",
  "Ritchie Lee Harbison.",
  "Marlon Lewis.",
  "Jamal Robbins.",
  "Muhammad Adbul Muhaymin.",
  "JR Williams.",
  "Darrien M. Barnhill.",
  "Sabin Marcus Jones.",
  "Deaundre Phillips.",
  "Marquez Warren.",
  "Nana Adomako.",
  "Jerome Keith Allen.",
  "Chad Robertson.",
  "Quanice Derrick Hayes.",
  "Raynard Burton.",
  "Chance David Baker.",
  "Lorenzo Antoine Cruz.",
  "Sherida Davis.",
  "Alteria Woods.",
  "Christopher Wade.",
  "Kenneth Johnson.",
  "Roderic Ronall Taylor.",
  "Jordan Edwards.",
  "Tashii S. Brown.",
  "Mark Roshawn Adkins.",
  "DeRicco DeVante Holdon.",
  "Jimmie Montel Sanders.",
  "Adam Trammell.",
  "Marc Brandon Davis.",
  "Joshua Terrell Crawford.",
  "Aaron Bailey.",
  "DeJuan Guillory.",
  "Euree Lee Martin.",
  "Brian Easley.",
  "Antonio Garcia Jr.",
  "Aries Clark.",
  "Thomas Williams.",
  "Herbert Gilbert.",
  "Devin Howell.",
  "Charles David Robinson.",
  "Anthony Antonio Ford.",
  "William Matthew Holmes.",
  "Stephen Gayle.",
  "Armando Frank.",
  "Dewboy Lister.",
  "Calvin Toney.",
  "Lawrence Hawkins.",
  "Keita O’Neil.",
  "Jean Pedro Pierre.",
  "Dennis Plowden.",
  "Thomas Yatsko.",
  "Warren Ragudo.",
  "Geraldine Townsend.",
  "Arthur McAfee Jr.",
  "Corey Mobley.",
  "Ronell Foster.",
  "Tre Ta’Quan Pringle Sr.",
  "Stephon Clark.",
  "Danny Day Thomas.",
  "Juan Markee Jones.",
  "Terrance Carlton.",
  "Marcus-David L. Peters.",
  "Robert Lawrence White.",
  "Antwon Michael Rose II.",
  "Anthony Marcell Green.",
  "Rashaun Washington.",
  "Cynthia Fields.",
  "Christopher Alexander Okamato.",
  "Joshua Wayne Harvey.",
  "James Leatherwood.",
  "Botham Shem Jean.",
  "Darell Richards.",
  "Antone G. Black Jr.",
  "Chinedu Valentine Okobi.",
  "Charles D. Roundtree Jr.",
  "Mahlon Edward Summerrour.",
  "Jesse Jesus Quinton.",
  "Andre Horton.",
  "George Robinson.",
  "D’ettrick Griffin.",
  "Jimmy Atchison.",
  "Mario Clark.",
  "Kevin Bruce Mason.",
  "Bishar Hasson.",
  "Marzues Scott.",
  "Marcus McVae.",
  "Julius Graves.",
  "Kevin Leroy Beasley Jr.",
  "Isaiah Lewis.",
  "Dominique Clayton.",
  "Ryan Twyman.",
  "Stephan Murray.",
  "Patricia Spivey.",
  "Channara Tom Pheap.",
  "Arthur Walton Jr.",
  "Byron Williams.",
  "Bennie Branch.",
  "Nicholas Walker.",
  "Jordan Michael Griffin.",
  "Maurice Holly.",
  "Atatiana Jefferson.",
  "Christopher Whitfield.",
  "Steven Day.",
  "Christopher McCorvey.",
  "Eric Reason.",
  "Michael Lorenzo Dean.",
  "Colby Clark.",
  "Tamir Rice.",
  "Freddie Gray.",
  "Alton Sterling.",
  "Deontae J. Keller.",
  "Oscar Grant.",
  "Sean Bell.",
  "Dontre Hamilton.",
  "Antonio Martin.",
  "Jeremy McDole.",
  "Meagan Hockaday.",
  "Tony Robinson.",
  "Kevin Matthews.",
  "Terrance Franklin.",
  "Miles Hall.",
  "William Green.",
  "Samuel David Mallard.",
  "E.J. Bradford.",
  "Sean Reed.",
  "Ariane McCree.",
  "Darius Tarver.",
  "Kwame Jones.",
  "De’von Bailey.",
  "Eric Logan.",
  "Jamarion Robinson.",
  "Gregory Hill Jr.",
  "JaQuavion Slaton.",
  "Brandon Webber.",
  "Willie McCoy.",
  "Jemel Roberson.",
  "DeAndre Ballard.",
  "Anthony Lamar Smith.",
  "Ramarley Graham.",
  "Manuel Loggins Jr.",
  "Wendell Allen.",
  "Kenderc McDade.",
  "Victor White.",
  "Kajieme Powell.",
  "Laquan McDonald.",
  "Mario Woods.",
  "Quintonio LeGrier.",
  "Gregory Gunn.",
  "Akiel Denkins.",
  "Terrence Sterling.",
  "Keith Scott.",
  "Lyanna Dior.",
  "Michelle Cusseaux.",
  "Matthew Ajibade.",
  "Frank Smart.",
  "Mya Hill.",
  "Alexia Christian.",
  "Victor Manuel Larosa.",
  "Joseph Mann.",
  "Billy Ray Davis.",
  "Michael Sabbie.",
  "Tyree Crawford.",
  "Michael Lee Marshall.",
  "Bennie Lee Tignor.",
  "Janet Wilson.",
  "Randy Nelson.",
  "Marco Loud.",
  "Darius Robinson.",
  "Mary Truxillo.",
  "Demarcus Semer.",
  "Willie Tillman.",
  "Terrill Thomas.",
  "Sylville Smith.",
  "Paul O'Neal.",
  "Pamela Turner."
  "Mouhamed Cisse",
  "Regis Korchinski-Paquet"
];
var x = document.getElementById("names");
  x.innerHTML = arrNames.join("</br>");
